apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
spec:
  selector:
    app: jellyfin-app
  ports:
  - port: 8096
    targetPort: 8096
    name: jellyfin-http
  - port: 8920
    targetPort: 8920
    name: jellyfin-https

